## Importing the Packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision =2)

## Importing the Data

In [3]:
raw_loan_data = np.genfromtxt('loan-data.csv', delimiter =';', skip_header = 1, autostrip = True)
raw_loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [4]:
np.isnan(raw_loan_data).sum()

88005

In [5]:
temp_fill = np.nanmax(raw_loan_data).round(2)+1

In [6]:
temp_mean = np.nanmean(raw_loan_data, axis =0).round(2)

C:\Users\faisa\AppData\Local\Temp\ipykernel_8408\1028928373.py:1: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_loan_data, axis =0).round(2)


In [7]:
temp_stats = np.array([np.nanmin(raw_loan_data, axis =0),
                       temp_mean,
                       np.nanmax(raw_loan_data, axis =0)])
temp_stats                       

C:\Users\faisa\AppData\Local\Temp\ipykernel_8408\2490614777.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_loan_data, axis =0),
C:\Users\faisa\AppData\Local\Temp\ipykernel_8408\2490614777.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_loan_data, axis =0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [8]:
column_str = np.argwhere(np.isnan(temp_mean)).squeeze()
column_str

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
column_num = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [10]:
loan_data_string = np.genfromtxt('loan-data.csv', 
                                 delimiter =';', 
                                 skip_header = 1, 
                                 autostrip = True, 
                                 usecols = column_str, 
                                 dtype =np.str)
loan_data_string

C:\Users\faisa\AppData\Local\Temp\ipykernel_8408\845402053.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype =np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
loan_data_numeric = np.genfromtxt('loan-data.csv', 
                                 delimiter =';', 
                                 skip_header = 1, 
                                 autostrip = True, 
                                 usecols = column_num, filling_values = temp_fill )
np.isnan(loan_data_numeric).sum()

0

### The Names of the Columns

In [12]:
header_name = np.genfromtxt('loan-data.csv', 
                                 delimiter =';', 
                                 skip_footer = raw_loan_data.shape[0], 
                                 autostrip = True, 
                                
                                 dtype = np.str)
header_name

C:\Users\faisa\AppData\Local\Temp\ipykernel_8408\3984872148.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
header_string = header_name[column_str]
header_num = header_name[column_num]

In [14]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [16]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [17]:
check_test = checkpoint('check_test', header_string, loan_data_string)
check_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

## Manipulating String Columns

In [18]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [19]:
header_string[0] = 'issue_date'
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [20]:
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [21]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [22]:
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0], '-15')
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [23]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [24]:
for i in range(13):
        loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i],
                                          i,
                                          loan_data_string[:,0])

In [25]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [26]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [27]:
status = np.array(['','Charged Off','Default','Late (31-120 days)'])
np.unique(np.isin(loan_data_string[:,1], (' ','Charged Off','Default','Late (31-120 days)')))

array([False,  True])

In [28]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1], (' ','Charged Off','Default','Late (31-120 days)')),0,1)

In [29]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [30]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [31]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [32]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2], ' months')
np.unique(loan_data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [33]:
loan_data_string[:,2] = np.where(np.isin(loan_data_string[:,2], ''),
                                 '60',
                                 loan_data_string[:,2])
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

In [34]:
header_string[2] = 'Term months'

### Grade and Subgrade

In [35]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [36]:
loan_data_string[:,4] = np.where(np.isin(loan_data_string[:,4],''),'H1',loan_data_string[:,4])
np.unique(loan_data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [37]:
loan_data_string[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

#### Removing Grade

In [38]:
header_string = np.delete(header_string,3)

In [39]:
loan_data_string = np.delete(loan_data_string,3,1)


In [40]:
header_string

array(['issue_date', 'loan_status', 'Term months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Converting Sub Grade

In [41]:
np.unique(loan_data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [42]:
keys = list(np.unique(loan_data_string[:,3]))                         
values = list(range(1, np.unique(loan_data_string[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [43]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [44]:
for i in np.unique(loan_data_string[:,3]):
        loan_data_string[:,3] = np.where(loan_data_string[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_string[:,3])

In [45]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [46]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [47]:
loan_data_string[:,4] = np.where(np.isin(loan_data_string[:,4],('', 'Not Verified')),0,1)

In [48]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [49]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [50]:
loan_data_string[:,5] = np.chararray.strip(loan_data_string[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [51]:
np.unique(loan_data_string[:,5], return_counts = True)

(array(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69'),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64))

In [52]:
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32), loan_data_string[:,5].astype(dtype = np.int32))

True

In [53]:
loan_data_string = np.delete(loan_data_string, 5,1)

In [54]:
header_string = np.delete(header_string,5)

In [55]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [56]:
header_string

array(['issue_date', 'loan_status', 'Term months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [57]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### State Address

In [58]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [59]:
header_string[5] = 'State Address'
header_string

array(['issue_date', 'loan_status', 'Term months', 'sub_grade', 'verification_status',
       'State Address'], dtype='<U19')

In [60]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5],''),0,loan_data_string[:,5])

In [61]:
np.unique(loan_data_string[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [62]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [63]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), 4, loan_data_string[:,5])

In [64]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [65]:
loan_data_string = loan_data_string.astype(dtype = int)

In [66]:
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [67]:
checkpoint_strings = ('checkpoint_strings',header_string,loan_data_string)

In [68]:
checkpoint_strings

('checkpoint_strings',
 array(['issue_date', 'loan_status', 'Term months', 'sub_grade', 'verification_status',
        'State Address'], dtype='<U19'),
 array([[ 5,  1, 36, 13,  1,  1],
        [ 0,  1, 36,  5,  1,  4],
        [ 9,  1, 36, 10,  1,  4],
        ...,
        [ 6,  1, 36,  5,  1,  1],
        [ 4,  1, 36, 17,  1,  3],
        [12,  1, 36,  4,  0,  3]]))

## Manipulating Numeric Columns

In [69]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Substitute "Filler" Values

In [70]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [71]:
temp_fill

68616520.0

In [72]:
np.isin(loan_data_numeric[:,0], temp_fill).sum()

0

#### Temporary Stats

In [73]:
temp_stats[:, column_num]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [74]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [75]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temp_fill, 
                                  temp_stats[0, column_num[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [76]:
temp_stats[0, column_num[3]]

6.0

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [77]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [78]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(np.isin(loan_data_numeric[:,i],temp_fill),temp_stats[2, column_num[i]], loan_data_numeric[:,i])

In [79]:
np.unique(np.isin(loan_data_numeric, temp_fill))

array([False])

### Currency Change

#### The Exchange Rate

In [80]:
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter =',', skip_header = 1, autostrip= True, usecols =3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [81]:
loan_data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [82]:
ex_rate = loan_data_string[:,0]

for i in range(1,13):
    ex_rate = np.where(ex_rate == i,
                       EUR_USD[i-1],
                       ex_rate)  
ex_rate = np.where(ex_rate == 0,
                    np.mean(EUR_USD),
                    ex_rate)  
ex_rate.shape


(10000,)

In [83]:
ex_rate = np.reshape(ex_rate,(10000,1))

In [84]:
loan_data_numeric = np.hstack((loan_data_numeric, ex_rate))

In [85]:
loan_data_numeric.shape

(10000, 7)

In [86]:
header_num = np.concatenate((header_num, np.array(['Exchange_rate'])))

In [87]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [88]:
col_dol = np.array([1,2,4,5])

In [89]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [90]:
for i in col_dol:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [91]:
loan_data_numeric.shape

(10000, 11)

#### Expanding the header

In [92]:
header_additional = np.array([column_name + '_EUR' for column_name in header_num[col_dol]])

In [93]:

header_num = np.concatenate((header_num, header_additional))

In [94]:
header_num


array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [95]:
header_num[col_dol] = np.array([column_name + '_USD' for column_name in header_num[col_dol]])

In [96]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'Exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [97]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [98]:
header_num = header_num[columns_index_order]

In [101]:
loan_data_numeric = loan_data_numeric[:,columns_index_order]

In [102]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate

In [99]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'Exchange_rate'],
      dtype='<U19')

In [104]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [105]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [106]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [107]:
checkpoint_numeric = ('checkpoint_numeric', header_num, loan_data_numeric)

In [109]:
checkpoint_numeric

('checkpoint_numeric',
 array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'Exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [112]:
checkpoint_strings

('checkpoint_strings',
 array(['issue_date', 'loan_status', 'Term months', 'sub_grade', 'verification_status',
        'State Address'], dtype='<U19'),
 array([[ 5,  1, 36, 13,  1,  1],
        [ 0,  1, 36,  5,  1,  4],
        [ 9,  1, 36, 10,  1,  4],
        ...,
        [ 6,  1, 36,  5,  1,  1],
        [ 4,  1, 36, 17,  1,  3],
        [12,  1, 36,  4,  0,  3]]))

In [114]:
loan_data = np.hstack((loan_data_numeric, loan_data_string))

In [115]:
header_full = np.concatenate((header_num, header_string))

In [117]:
loan_data.shape

(10000, 17)

In [118]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'Exchange_rate',
       'issue_date', 'loan_status', 'Term months', 'sub_grade', 'verification_status',
       'State Address'], dtype='<U19')

In [121]:
np.isnan(loan_data).sum()

0

## Sorting the New Dataset

In [122]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [123]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       36.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

## Storing the New Dataset

In [125]:
loan_data = np.vstack((header_full, loan_data))

In [126]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'State Address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '36.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [127]:
np.savetxt('Loan-data-processed.csv', loan_data, fmt ='%s', delimiter = ',')